server.address=127.0.0.1
server.port=8080
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=33MB
server.error.include-message=always
streaming.sessions=data/sessions
streaming.timeout-seconds=300
